Completion of otpverification
TechStarsCommunity/FE-Online_Library pull request #82
Opened 2023-09-05 13:32 UTC by ItzAbraham

# *Pull Request Template*

## Description (*What does this PR do?*)

Please provide a brief description of the changes introduced by this pull request.

## Related Issue(s)

- [ ] Issue 1
- [ ] Issue 2

## Checklist

- [ ] I have tested the changes locally and they work as expected.
- [ ] The code follows the project's coding standards and conventions.
- [ ] I have added appropriate comments and documentation where necessary.
- [ ] All tests passed successfully.
- [ ] I have updated the necessary dependencies.
- [ ] I ran ``` npm run build ``` and it built without errors

## Changes Made

Please provide a list of the main changes made in this pull request.

## Screenshots

If applicable, add screenshots or GIFs to showcase the changes visually.

## Dependencies or File Changes

Please list any new dependencies or files added or updated in this pull request.

## Testing Instructions

Please provide clear instructions on how to test the changes made in this pull request.

## Additional Notes

Add any additional notes or context that may be helpful for the reviewer.

2023-09-06 09:50 UTC, Christiano112 commented on src/pages/otpverification.jsx
> +                    <form onSubmit={handleSubmit(onSubmit)} className="right-section"></form>
why is the form element closing here?

2023-09-06 09:51 UTC, Christiano112 requested changes
fix the form element closing tag

2023-09-07 20:40 UTC, ItzAbraham commented on src/pages/otpverification.jsx
> +                    <form onSubmit={handleSubmit(onSubmit)} className="right-section"></form>
I have adjust that Boss.

2023-09-10 16:47 UTC, Christiano112 approved these changes

2023-09-10 16:47 UTC, merged