profile form right hand side
TechStarsCommunity/FE-Online_Library pull request #88
Opened 2023-09-11 12:53 UTC by tundeloper

# *Pull Request Template*

## Working on profile section right-hand-side

this changes add ```profile``` route to the route file

## Related Issue(s)

- [ ] Issue 1
- [ ] Issue 2

## Checklist

- [ ] I have tested the changes locally and they work as expected.
- [ ] The code follows the project's coding standards and conventions.
- [ ] I have added appropriate comments and documentation where necessary.
- [ ] All tests passed successfully.
- [ ] I have updated the necessary dependencies.
- [ ] I ran ``` npm run build ``` and it built without errors

## Changes Made

Please provide a list of the main changes made in this pull request.
added profile routes,
added css file to the style directory
added settings svg to the public directory
added profile background image to the public directory 

## Screenshots

If applicable, add screenshots or GIFs to showcase the changes visually.

## Dependencies or File Changes
src/route
src/pages/profile.jsx
src/styles/profile.css
public directory

# Please list any new dependencies or files added or updated in this pull request.

src/profile
public/bgimage.png
public/settingSvg.jsx

## Testing Instructions

Please provide clear instructions on how to test the changes made in this pull request.
go to /profile to see the changes made

## Additional Notes

2023-09-12 14:01 UTC, Christiano112 requested changes

2023-09-12 14:01 UTC, Christiano112 commented on src/components/header.jsx
Is this the updated content of the header file?

2023-09-12 14:01 UTC, Christiano112 commented on src/components/loading.jsx
Delete the comments

2023-09-12 14:01 UTC, Christiano112 commented on src/pages/home.jsx
I don't think your branch is updated.... kindly review your work

2023-09-15 23:31 UTC, tundeloper commented on src/pages/home.jsx
okay

2023-09-16 04:19 UTC, Christiano112 commented
Your codebase isn't updated with the current code on develop

2023-09-16 04:19 UTC, closed without merging